// Generated by gencpp from file test_package/AddTwoInts.msg
// DO NOT EDIT!


#ifndef TEST_PACKAGE_MESSAGE_ADDTWOINTS_H
#define TEST_PACKAGE_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <test_package/AddTwoIntsRequest.h>
#include <test_package/AddTwoIntsResponse.h>


namespace test_package
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace test_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test_package::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::test_package::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::test_package::AddTwoInts > {
  static const char* value()
  {
    return "test_package/AddTwoInts";
  }

  static const char* value(const ::test_package::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::test_package::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::test_package::AddTwoInts > 
template<>
struct MD5Sum< ::test_package::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test_package::AddTwoInts >::value();
  }
  static const char* value(const ::test_package::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_package::AddTwoIntsRequest> should match 
// service_traits::DataType< ::test_package::AddTwoInts > 
template<>
struct DataType< ::test_package::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::test_package::AddTwoInts >::value();
  }
  static const char* value(const ::test_package::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test_package::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::test_package::AddTwoInts > 
template<>
struct MD5Sum< ::test_package::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test_package::AddTwoInts >::value();
  }
  static const char* value(const ::test_package::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_package::AddTwoIntsResponse> should match 
// service_traits::DataType< ::test_package::AddTwoInts > 
template<>
struct DataType< ::test_package::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::test_package::AddTwoInts >::value();
  }
  static const char* value(const ::test_package::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_PACKAGE_MESSAGE_ADDTWOINTS_H
